// Generated by CoffeeScript 1.3.3
(function() {

  Number.prototype.seconds = function() {
    return this.valueOf() * 1000;
  };

  Number.prototype.minutes = function() {
    return this.valueOf() * 60..seconds();
  };

  Number.prototype.hours = function() {
    return this.valueOf() * 60..minutes();
  };

  Number.prototype.days = function() {
    return this.valueOf() * 24..hours();
  };

  Number.prototype.months = function() {
    return this.valueOf() * 30..days();
  };

  Number.prototype.years = function() {
    return this.valueOf() * 365..days();
  };

  Number.prototype.ago = function() {
    return new Date(new Date().valueOf() - this.valueOf());
  };

  Number.prototype.since = function() {
    return new Date(new Date().valueOf() + this.valueOf());
  };

  Number.prototype.second = Number.prototype.seconds;

  Number.prototype.minute = Number.prototype.minutes;

  Number.prototype.hour = Number.prototype.hours;

  Number.prototype.day = Number.prototype.days;

  Number.prototype.month = Number.prototype.months;

  Number.prototype.year = Number.prototype.years;

  Number.prototype.fromNow = Number.prototype.since;

}).call(this);
